### PR TITLE
realtek-poe/openwrt: Generate config from board.json

### PR DESCRIPTION
**Pull request by Hurricos**
Styled after work provided by @svanheule, then reiterated by @howels.

Before this commit, realtek-poe maintainers prioritized keeping realtek-poe simple; it was "[a tool to] take a config file and control the hardware ... [which speaks] UCI config on one end, and PoE protocol on the other"[^1]. We declined to support generating that config file previously.

OpenWrt maintainer @blogic firmly disagreed[^2], because OpenWrt users were finding their devices starting with non-functional PoE (which is a violation of the principle of least surprise).

It's been about a year since a solution to this problem was first provided[^3].

Change stance. Now, begin generating /etc/config/poe from board.json under OpenWrt (our only supported platform). It's in the community's best interest to at least provide a stop-gap until either:

- other software actually uses realtek-poe outside of OpenWrt, or
- another OpenWrt package uses /etc/config/poe to configure these PSEs

at which point I'll revisit and do the integration work.

A companion commit will be required to openwrt/packages.git.

Signed-off-by: Martin Kennedy <hurricos@gmail.com>

[^1]: https://github.com/Hurricos/realtek-poe/issues/41#issuecomment-2426670039

[^2]: https://github.com/openwrt/openwrt/pull/16838#issuecomment-2542114739

[^3]: https://github.com/Hurricos/realtek-poe/pull/31

Replaces: #31

### CODE REVIEW

**Comment by Hurricos** [comment]
@mrnuke, @svanheule: on a scale from 0 to incredible psychic pain, how much hurt does this PR cause you?

My take: let's get something out-the-door, to staunch the bleeding in time for the OpenWrt 24 final builds.

**Review by howels — APPROVED** [review]

**Comment by howels** [comment]
A pragmatic solution, thanks.

**Comment by mrnuke** [comment]
I don't think asking for an opinion from the main contributors and then only giving them 50 minutes to respond before merging something is reasonable or collaborative.

As a separate project, realtek-poe is upstream to OpenWRT. It's also a special relationship because they are realtek-poe's only downstream user. Be it as it may, while downstream projects may request and influence upstreams, they don't get to dictate what upstream does. I disagree with @blogic, and I do not find any objective argument in his request that realtek-poe takes on the responsibility of parsing an arbitrary JSON format.

I am of the mindset of do one thing and do it well. And by pushing this commit, this principle has been violated.

**Comment by Hurricos** [comment]
> I don't think asking for an opinion from the main contributors and then only giving them 50 minutes to respond before merging something is reasonable or collaborative.

Partially fixed with 89686c9d625ab515868a8152dc5010e338435784.

**Comment by svanheule** [comment]
Placing the uci-defaults script in the packages feed seems like a decent intermediate solution to me. That way the config format stays specific to poe-realtek, until we get a better understanding of common requirements.

**Pull request merged**
