### PR TITLE
realtek-poe: De-mistify the "unknown" bug

### PR DESCRIPTION
**Pull request by mrnuke**
Off-by-one error caused the status to be reported as UFO instead of "Requesting Power".

General feeling on the [OpenWRT forum](https://forum.openwrt.org/t/bringing-support-for-realtek-poe-to-mainline-openwrt/127777/83?u=mrnuke) about this change is positive.

### CODE REVIEW

**Comment by mrnuke** [comment]
@Hurricos, any chance we could set the repo for "Rebase and Merge" by default, instead of "Create a merge commit" ?

**Comment by Hurricos** [comment]
Awaiting f12e9dbbcff95ec699cdb1e05f6c579992ee826a as a separate PR (very soon!)

**Comment by Hurricos** [comment]
Not intentionally closed, looks like. Merging this will thankfully only add the two meaningful commits.

**Comment by Hurricos** [comment]
... though @mrnuke -- please correct me if I am wrong and this closure was intentional.

**Comment by mrnuke** [comment]
This closure was accidental. OOPS!

**Comment by Hurricos** [comment]
Merged. Thanks!

**Comment by mrnuke** [comment]
Apparently `gut push origin :some-branch` also closes the associated PRs

**Pull request merged**
